# Generated by Django 4.2.1 on 2023-09-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_followercounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerCounts',
            new_name='FollowersCount',
        ),
    ]
